### ISSUE TITLE
Allow assets to be links

### ISSUE THREAD

**Issue by janhohenheim** [bash/gilderoy#3]
```toml
[assets.pic]
source = "https://avatars2.githubusercontent.com/u/9047632"
```
This does not work at the moment, as gilderoy expects all assets to be local files.
